name = "tic-tac-toe-lean"
version = "0.1.0"
defaultTargets = ["tic-tac-toe-lean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[lean_lib]]
name = "TicTacToeLean"

[[lean_exe]]
name = "tic-tac-toe-lean"
root = "Main"
